rvm:
  - 1.8.7
  - 1.9.3
  - jruby
gemfile:
  - gemfiles/activesupport-3.0.gemfile
  - gemfiles/activesupport-3.1.gemfile
  - gemfiles/activesupport-3.2.gemfile

notifications:
  recipients:
    - lukas@at-point.ch
